### ISSUE TITLE
Перевод данных из массива PHP в формат JSON

### ISSUE THREAD

**Issue by johnynsk** [sibsutis-zp51-coolteam/timetable#13]
Необходимо написать перевод данных из массива PHP в формат JSON.
1. Сгенерировать массив циклом.
2. Составить массив самому (в интернете много описаний задания массива вручную).

Созданный вручную массив должен быть многоуровневым (2-3 уровня вложенности)

Вывести на экран.
Сохранить в файл одной командой.

JSON делается из массива одной функцией.

Оформленную функцию вывода и сохранения в файл реализовать двумя различными методами класса.

**Comment by Shamann1101** [comment]
Нет времени на реализацию
